name: Delete Old Branches 10 mins

on:
  pull_request:
    branches:
      - Develop
      - Master

jobs:
  delete_old_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Bash script to delete branches older than 10 minutes
        run: |
          git fetch --prune
          current_time=$(date +%s)

          # Loop through all remote branches
          for branch in $(git branch -r | grep -v HEAD | grep -v Develop | grep -v Master | sed '/\*/d'); do
            remote_branch=$(echo ${branch} | sed 's#origin/##')
            
            # Get the timestamp of the last commit in the branch
            last_commit_time=$(git show -s --format=%ct ${branch})
            branch_age_minutes=$(( (current_time - last_commit_time) / 60 ))

            # Check if the branch is merged into Develop or Master
            is_merged_to_Develop=$(git branch --contains ${branch} origin/Develop 2>/dev/null || echo "false")
            is_merged_to_Master=$(git branch --contains ${branch} origin/Master 2>/dev/null || echo "false")

            # Check if a pull request exists for the branch
            pr_count=$(gh pr list --head ${remote_branch} --json number --jq 'length')

            if [ ${branch_age_minutes} -gt 10 ] && ([ "$is_merged_to_Develop" == "true" ] || [ "$is_merged_to_Master" == "true" ]) && [ ${pr_count} -eq 0 ]; then
              echo "Branch $branch is merged and older than 10 minutes. Deleting."
              git push origin --delete ${remote_branch}
            else
              echo "Branch $branch does not meet the deletion criteria."
            fi
          done
