name: Delete Old Branches 10 mins

on:
  pull_request:
    branches:
      - Develop

permissions:
  contents: write

jobs:
  delete_old_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Bash script to delete branches older than 10 minutes
        run: |
          git fetch --prune
          # Loop through all remote merged branches
          for branch in $(git branch -r | grep -v HEAD | grep -v Develop | grep -v Master | grep -v Feature-1 | grep -v Feature-2 | grep -v Feature-3 | grep -v Feature-4 | sed '/\*/d'); do
            if [ -z "$(git log -1 --since='10 minutes ago' -s ${branch})" ]; then
              echo "Branch $branch is older than 10 minutes."
              echo -e "$(git show --format='%ci %cr %an' ${branch} | head -n 1) \t $branch"
              remote_branch=$(echo ${branch} | sed 's#origin/##')
              # Uncomment the following line to delete the branch
              git push origin --delete ${remote_branch}
            else
              echo "Branch $branch is not older than 10 minutes."
            fi
          done
