name: Delete Old Branches 10 mins

on:
  pull_request:
    branches:
      - Develop

jobs:
  delete_old_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Bash script to delete branches older than 3 months
        run: |
          git fetch --prune
          # Loop through all remote merged branches
          for branch in $(git branch -r | grep -v HEAD | grep -v develop | grep -v master | sed '/\*/d'); do
            if [ -z "$(git log -1 --since='3 months ago' -s ${branch})" ]; then
              echo "Branch $branch is older than 3 months."
              echo -e "$(git show --format='%ci %cr %an' ${branch} | head -n 1) \t $branch"
              remote_branch=$(echo ${branch} | sed 's#origin/##')
              # Uncomment the following line to delete the branch
              git push origin --delete ${remote_branch}
            else
              echo "Branch $branch is not older than 3 months."
            fi
          done
