name: .NET Unit Tests

on:
  pull_request:
    branches:
      - develop  # Trigger only when the PR targets the develop branch
    types: [opened, synchronize, reopened]  # Trigger for these PR events

jobs:
  test:
    runs-on: ubuntu-latest  # You can change the OS if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'  # Replace with the version of .NET you're using

      - name: Disable .NET CLI telemetry
        run: echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore

      - name: Run unit tests
        run: dotnet test --no-restore
